In [35]:
import pandas as pd
import numpy as np
df = pd.DataFrame({'1': list('abc'), 2: [None, '', np.nan], 3: [4, 5, 6]}, index=list('xyz'))
df

      2  3  1
x  None  4  a
y        5  b
z   NaN  6  c

In [36]:
~ pd.isnull(df[2])

x    False
y     True
z    False
Name: 2, dtype: bool

In [42]:
df[['1', 2]].isnull()

       1      2
x  False   True
y  False  False
z  False   True

In [44]:
df[['1', 2]].notnull()

      1      2
x  True  False
y  True   True
z  True  False

In [43]:
df[['1', 2]].isnull().any(axis=1)

x     True
y    False
z     True
dtype: bool